package hpnj.mediatruck.model;

public enum Role {
    ACTOR,
    ARTIST,
    AUTHOR,
    CINEMATOGRAPHER,
    COMPOSER,
    COSTUME_DESIGNER,
    DEVELOPER,
    DESIGNER,
    DIRECTOR,
    EDITOR,
    MAKEUP_ARTIST,
    MUSICIAN,
    PROGRAMMER,
    PRODUCER,
    SCREENWRITER,
    SOUND_DESIGNER,
    SPECIAL_EFFECTS_ARTIST,
    STUNTMAN,
    VISUAL_EFFECTS_ARTIST,
    WRITER,
}